require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires a Product -> Clean Build
install! 'cocoapods', :deterministic_uuids => false

target 'App' do
  capacitor_pods
  # Add your Pods here
end
